# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('subsec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezyapp.SubSection')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezyapp.Tests')),
            ],
        ),
        migrations.AddField(
            model_name='testresponses',
            name='subsec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ezyapp.SubSection'),
            preserve_default=False,
        ),
    ]
