# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezyapp', '0002_auto_20160108_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_id',
        ),
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(to='ezyapp.Student'),
        ),
    ]
