# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezyapp', '0004_auto_20160203_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezyapp.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezyapp.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezyapp.Tests')),
            ],
        ),
    ]
