# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezyapp', '0005_testresponses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresponses',
            name='option',
        ),
        migrations.AddField(
            model_name='testresponses',
            name='option_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
