# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='class_id',
            new_name='sudent',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='tserver_id',
            new_name='tserver',
        ),
        migrations.RenameField(
            model_name='testserver',
            old_name='class_id',
            new_name='classobj',
        ),
        migrations.RenameField(
            model_name='testserver',
            old_name='paper_id',
            new_name='paper',
        ),
    ]
