# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezyapp', '0002_auto_20160123_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='sudent',
            new_name='student',
        ),
    ]
