# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezyapp', '0003_auto_20160123_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
